android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official

org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -Dlint.nullness.ignore-deprecated=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true


## Maven Central Publication ##
systemProp.org.gradle.internal.publish.checksums.insecure=true
systemProp.org.gradle.internal.http.socketTimeout=120000

# Maven coordinates (final)
GROUP=io.github.joelromanpr

# Project URLs
POM_URL=https://github.com/joelromanpr/tiny-compressor-ktx
POM_SCM_URL=https://github.com/joelromanpr/tiny-compressor-ktx
POM_SCM_CONNECTION=scm:git:https://github.com/joelromanpr/tiny-compressor-ktx.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/joelromanpr/tiny-compressor-ktx.git

# License
POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_LICENCE_DIST=repo

# Developer
POM_DEVELOPER_ID=joelromanpr
POM_DEVELOPER_NAME=Joel Roman
POM_DEVELOPER_URL=https://github.com/joelromanpr
POM_DEVELOPER_EMAIL=contact@joelromanpr.com

# Sonatype Central
SONATYPE_HOST=CENTRAL_PORTAL
SONATYPE_AUTOMATIC_RELEASE=true